backend:
  name: github
  branch: main
  repo: AkaKeliner/mdm-helper

site_url: https://help.api-mdm.prox2.dex-it.ru

publish_mode: editorial_workflow

media_folder: "static/img"
public_folder: "/img/"

collections:
  - name: "help"
    label: "Help Center"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Контент", name: "body", widget: "markdown" }
  - name: blog
    label: "blog"
    folder: blog
    identifier_field: title
    extension: md
    widget: "list"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }
      - { name: slug, label: Slug, widget: string }
      - label: "Tags"
        name: "tags"
        widget: "list"
      - label: "Authors"
        name: "authors"
        widget: "list"
        fields:
          - { name: name, label: Name, widget: string }
          - { name: title, label: Title, widget: string }
          - { name: url, label: URL, widget: string }
          - { name: imageUrl, label: ImageURL, widget: string }
