backend:
  name: github
  branch: main
  repo: git@github.com:AkaKeliner/mdm-helper.git

media_folder: "static/img"
public_folder: "/img/"

collections:
  - name: "help"
    label: "Help Center"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Контент", name: "body", widget: "markdown" }
